### ISSUE TITLE
Parameter Sliders for Variable Fonts (Bahnschrift, etc.)

### ISSUE THREAD

**Issue by be5invis** [character-map-uwp/Character-Map-UWP#109]
Variable fonts like Bahnschrift can vary its weight/width/other properties continuously. It would be great that Character Map can provide sliders when a font is variable.

`IDWriteFontFace5` and `IDWriteFontResource` has methods to query variation axes, as well as getting/setting variation coordinates.

**Comment by JohnnyWestlake** [comment]
The main problem here is the UI layer (UWP XAML) doesn't let you set any variable properties on Fonts or Text fields. Underneath at the DirectWrite layer it's all there, but not in the Windows UI layer (and there's no interop to get the underlying DirectX resources from the XAML layer yet).

Like a lot of these tied to the UI layer, the solution is to either wait for Microsoft to release WinUI 3 (the open source variant of XAML, so that we can actually fix this properly at the UI layer), or re-write the character map grid entirely in DirectX (which is not impossible but leads to *lot* of extra work around input and keyboards and GPU handling and accessibility), or replace the text rendering with a custom one (which I've tried, and did not have good performance or memory usage).

At the moment I'm not likely to attempt the DirectX rewrite (though anyone can feel free), and WinUI3 is at least 6 months away.

**Comment by JohnnyWestlake** [comment]
(Full support for variable OpenType Axis for **_Type Ramp view only_** is currently in the [Character-Map-UWP/Variations-Basic](https://github.com/character-map-uwp/Character-Map-UWP/tree/Variations-Basic) dev branch)

**Comment by JohnnyWestlake** [comment]
Thanks to Edi for publishing this is now in the current app for Type Ramp view only - with a caveat that it doesn't seem to work properly for imported fonts / fonts not actually "installed" in Windows. Not certain whether this is something strange in the FontLoader Win2D uses underneath or a bug in DirectWrite for custom font loaders - requires some investigating. Which probably involves just writing our own FontSet loader and skipping CanvasFontSet.

**Comment by be5invis** [comment]
@JohnnyWestlake 
If you can get the `IDWriteFontFace`, you can try to QI it to `IDWriteFontFace5` and use the `IDWriteFontResource` APIs to create a `IDWriteFontFace5` with variation applied.

**Comment by JohnnyWestlake** [comment]
Fwiw, it does currently work with *everything* that comes from the system font set fine. But as soon as you involve either a custom font loader (as Win2D uses) or use your own IDWriteFontSetBuilder2 from IDWriteFactory7 it seems to fail, but *only* on certain fonts.

With IDWriteFontSetBuilder2, fonts like Banchshrift and Lora and Gimlet X-Ray and Tilt Prism work perfectly fine with all of their variable axis, but the rare few like Inter V will only render on the named Axis values (i.e the values used for it's named faces), but won't render any variations in-between.

Just trying to contact someone who works on DirectWrite to see if it's a known issue.

**Comment by be5invis** [comment]
@JohnnyWestlake Well, the stock Inter V's `STAT` table is broken... See https://github.com/rsms/inter/issues/265
You can try [Source Serif Variable](https://github.com/adobe-fonts/source-serif-pro)'s latest version which has a functioning `STAT` table.
Certain variable fonts are exotic. One example is [Zinzin VF](https://v-fonts.com/fonts/zinzin-vf) which has a huge `rvrn` feature that adds more swash when you increase the value of `SWSH` axis.

**Comment by be5invis** [comment]
If you want to test the *patched* Inter V, use the file below.
[📄 Inter-V.zip](https://github.com/character-map-uwp/Character-Map-UWP/files/4624761/Inter-V.zip)

**Comment by JohnnyWestlake** [comment]
Same issue with the patched font unfortunately - works fine if installed via the system, only renders the named axis when coming through IDWriteFontSetBuilder or through Win2D's custom IDWriteFontLoader.

The only other variable font I've noticed this problem with it [ArrowType's Recursive](https://github.com/arrowtype/recursive/) - clearly DirectWrite knows how to handle both fonts perfectly fine because they work fine when installed, but I'll see if my contact knows anything and keeping playing with different ideas.

(Zinzin VF works fine coming from either source)

**Comment by JohnnyWestlake** [comment]
For investigation purposes: 
- All the variable font's with issues use SLNT axis.
- Only the first named face renders with the proper font, or allows variations to be applied. All other names faces fallback to Segoe UI.
- Same issue in XAML - only the first named variant renders (and if XAML is bugged out too, leads me to believe it's a DirectWrite bug)

**Comment by be5invis** [comment]
I tested all the fonts with Dwayne's thing (https://github.com/fdwr/TextLayoutSampler) and they all worked perfectly. His font loading code could be found here: https://github.com/fdwr/TextLayoutSampler/blob/5cebb9fa447000912c389fba6f7008f0342e765d/DWritEx.ixx#L778.
