### ISSUE TITLE
Settings Screen Acrylic region

### ISSUE THREAD

**Issue by mdtauk** [character-map-uwp/Character-Map-UWP#135]
![image](https://user-images.githubusercontent.com/7389110/88558839-0042cf80-d024-11ea-9777-11c8db042528.png)

Not sure if this is intentional or a bug, but there is an area of Host Backdrop Acrylic used on the settings page which appears out of place.

**Comment by ray1997** [comment]
Maybe the intention was to imitate the actual side menu by using acrylic effect.
Or maybe it was copy & pasted over from side menu and didn't check.
Or maybe because default background color of it is black and it blend with background,
Either way, replacing `Background="{StaticResource DefaultHostBrush}"` with `Background="{ThemeResource ApplicationPressedForegroundThemeBrush}"` should make it distinct from the background if it was the later cases.
Otherwise, it gonna stay the same.
@JohnnyWestlake @EdiWang So.. Keep it acrylic or change to gray?

**Comment by JohnnyWestlake** [comment]
From my point of view I did this intentionally as it's the background used in the actual font list and I wanted the preview to match

**Comment by mdtauk** [comment]
> From my point of view I did this intentionally as it's the background used in the actual font list and I wanted the preview to match

It feels a little odd to "cut out" a hole in the app to display a preview of fonts.  I wonder if it wouldn't be better to use the same kind of Acrylic used by the context menus, or just leave it with a border brush, like the preview above.

![image](https://user-images.githubusercontent.com/7389110/88687005-a0195f80-d0ef-11ea-92ec-08c3c4a906e8.png)
