### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by KristofKekesi** [character-map-uwp/Character-Map-UWP#153]
## Hello Sir.
I would like to translate it to Hungarian (hu-HU). Should you make to required files for me please?
I translated UWP apps before, I know the process well.  If you want to check my prevous translations check at https://www.kekesi.dev/skills/translation/.

**Comment by ray1997** [comment]
If you wish to translate here's a file for Hungarian language. You could also send pull request if you know the process, otherwise, download it from link below.
https://github.com/ray1997/Character-Map-UWP/blob/translation-update/CharacterMap/CharacterMap/MultilingualResources/CharacterMap.hu-HU.xlf

**Comment by KristofKekesi** [comment]
Thanks. I'll make a pull requst when I'm done.
